/****** Object:  Function [dbo].[fn_GetSecondWord]    Committed by VersionSQL https://www.versionsql.com ******/

create FUNCTION dbo.fn_GetSecondWord( @IN AS VARCHAR(8000))
RETURNS VARCHAR( 50)
AS
BEGIN
-- INITIAL TRIM AND NULL HANDLING
DECLARE @TEMP  VARCHAR(8000) = LTRIM( RTRIM( ISNULL( @IN, '')));
-- FIX EXTRA SPACES AROUND SECOND WORD
SET @TEMP = LTRIM( SUBSTRING( @TEMP, CHARINDEX(' ', @TEMP), 8000));
-- ANY MORE SPACES
DECLARE @END INT = CHARINDEX(' ', @TEMP);
-- REMOVE EVERYTHING AFTER NEXT SPACE
IF @END > 0
SET @TEMP = SUBSTRING( @TEMP, 1, CHARINDEX(' ', @TEMP) - 1);

RETURN @TEMP;
END
