/****** Object:  Table [dbo].[CategoryScore]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CategoryScore](
	[Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[RssFeedItemId] [int] NOT NULL,
	[CategoryId] [int] NOT NULL,
	[Score] [decimal](20, 10) NULL,
	[TagId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [Ak_CategoryScore] UNIQUE NONCLUSTERED 
(
	[RssFeedItemId] ASC,
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [idx_CategoryScore_Score] ON [dbo].[CategoryScore]
(
	[Score] ASC
)
INCLUDE([RssFeedItemId],[CategoryId]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[CategoryScore]  WITH CHECK ADD  CONSTRAINT [Fk_CategoryScore_Category] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Category] ([Id])
ALTER TABLE [dbo].[CategoryScore] CHECK CONSTRAINT [Fk_CategoryScore_Category]
ALTER TABLE [dbo].[CategoryScore]  WITH NOCHECK ADD  CONSTRAINT [FK_Tag_CategoryScore] FOREIGN KEY([TagId])
REFERENCES [dbo].[Tag] ([Id])
NOT FOR REPLICATION 
ALTER TABLE [dbo].[CategoryScore] CHECK CONSTRAINT [FK_Tag_CategoryScore]
