/****** Object:  Table [dbo].[Category]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Category](
	[Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[LabelId] [int] NOT NULL,
	[IndustryId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [Ak_Category] UNIQUE NONCLUSTERED 
(
	[LabelId] ASC,
	[IndustryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[Category]  WITH CHECK ADD  CONSTRAINT [Fk_Category_Label] FOREIGN KEY([LabelId])
REFERENCES [dbo].[Label] ([Id])
ALTER TABLE [dbo].[Category] CHECK CONSTRAINT [Fk_Category_Label]
