/****** Object:  Table [dbo].[Topic]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Topic](
	[Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[RssFeedItemId] [int] NOT NULL,
	[Label] [varchar](max) NOT NULL,
	[WikiLink] [varchar](max) NULL,
	[Score] [decimal](20, 10) NULL,
 CONSTRAINT [PK__TOPIC__3214EC07C97F52D1] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE NONCLUSTERED INDEX [_dta_index_Topic_5_1614628795__K2_1_3_4_5] ON [dbo].[Topic]
(
	[RssFeedItemId] ASC
)
INCLUDE([Id],[Label],[WikiLink],[Score]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[Topic]  WITH NOCHECK ADD  CONSTRAINT [Fk_Topic_RssFeedItem] FOREIGN KEY([RssFeedItemId])
REFERENCES [dbo].[RssFeedItem] ([Id])
NOT FOR REPLICATION 
ALTER TABLE [dbo].[Topic] CHECK CONSTRAINT [Fk_Topic_RssFeedItem]
