/****** Object:  View [InboundCRM].[FinalEnrichedData]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [InboundCRM].[FinalEnrichedData]
AS
SELECT        II.ID, II.FirstName, II.LastName, II.PhoneNumber, II.Email, cast(ii.inserteddate as date) inserteddate, II.Country, II.CompanyName, IE.FirstName AS EnrichedFirstName, IE.LastName AS EnrichedLastName, II.Gender, IE.Designation, 
                         IE.EmployerName, II.EmailVerificationStatus, IE.LinkedinURL, II.IsPersonalEmail, IE.Country AS EnrichedCountry, I.Name AS IndustryName, O.glassDoorIndustry as GlassDoorIndustry, O.Revenue, CASE WHEN ROW_NUMBER() OVER (PARTITION BY 
                         IE.FirstName, IE.LastName, IE.EmployerName
ORDER BY II.CreatedDate) = 1 THEN 'N' ELSE 'Y' END AS Revisit_Person, CASE WHEN ROW_NUMBER() OVER (PARTITION BY IE.EmployerName
ORDER BY II.CreatedDate) = 1 THEN 'N' ELSE 'Y' END AS Revisit_Company, o.websiteTitle, o.websiteKeywords, o.websiteDescription,
case when charindex('fast credit',o.websiteDescription)>0 then 'Yes'
when charindex('fast loan',o.websiteDescription)>0 then 'Yes'
when charindex('Spa Deals',o.websiteDescription)>0 then 'Yes'
when charindex('fitness deals',o.websiteDescription)>0 then 'Yes'
when charindex('one stop fashion',o.websiteDescription)>0 then 'Yes'
when charindex('watch latest',o.websiteDescription)>0 then 'Yes'
when charindex('food deals',o.websiteDescription)>0 then 'Yes'
when charindex('online grocery',o.websiteDescription)>0 then 'Yes'
when charindex('popular fashion',o.websiteDescription)>0 then 'Yes'
when charindex('shopper',o.websiteDescription)>0 then 'Yes'
when charindex('food delivery',o.websiteDescription)>0 then 'Yes'
when charindex('live score',o.websiteDescription)>0 then 'Yes'
when charindex('booking flights',o.websiteDescription)>0 then 'Yes'
when charindex('book taxi',o.websiteDescription)>0 then 'Yes'
when charindex('instant money transfer',o.websiteDescription)>0 then 'Yes'
when charindex(' App ',o.websiteDescription)>0 then 'Yes'
when charindex('Shopping',o.websiteDescription)>0 then 'Yes'
when charindex('Online',o.websiteDescription)>0 then 'Yes'
when charindex('Retail',o.websiteDescription)>0 then 'Yes'
when charindex('Mobile',o.websiteDescription)>0 then 'Yes'
when charindex('Songs Download',o.websiteDescription)>0 then 'Yes'
when charindex('Platform',o.websiteDescription)>0 then 'Yes'
when charindex('Shopping Cart',o.websiteDescription)>0 then 'Yes'
when charindex('omni-channel',o.websiteDescription)>0 then 'Yes'
when charindex('e-commerce',o.websiteDescription)>0 then 'Yes'
when charindex('telecom',o.websiteDescription)>0 then 'Yes'
when charindex('travel',o.websiteDescription)>0 then 'Yes'
when charindex('tourism',o.websiteDescription)>0 then 'Yes'
when charindex('BFSI',o.websiteDescription)>0 then 'Yes'
when charindex('songs online',o.websiteDescription)>0 then 'Yes'
when charindex('rummy online',o.websiteDescription)>0 then 'Yes'
when charindex('Online banking',o.websiteDescription)>0 then 'Yes'
when charindex('telecom services provider',o.websiteDescription)>0 then 'Yes'
when charindex('no credit card needed',o.websiteDescription)>0 then 'Yes'
when charindex('buy online',o.websiteDescription)>0 then 'Yes'
when charindex('music for everyone',o.websiteDescription)>0 then 'Yes'
when charindex('fast credit',o.WebsiteKeywords)>0 then 'Yes'
when charindex('fast loan',o.websiteKeywords)>0 then 'Yes'
when charindex('Spa Deals',o.websiteKeywords)>0 then 'Yes'
when charindex('fitness deals',o.websiteKeywords)>0 then 'Yes'
when charindex('one stop fashion',o.websiteKeywords)>0 then 'Yes'
when charindex('watch latest',o.websiteKeywords)>0 then 'Yes'
when charindex('food deals',o.websiteKeywords)>0 then 'Yes'
when charindex('online grocery',o.websiteKeywords)>0 then 'Yes'
when charindex('popular fashion',o.websiteKeywords)>0 then 'Yes'
when charindex('shopper',o.websiteKeywords)>0 then 'Yes'
when charindex('food delivery',o.websiteKeywords)>0 then 'Yes'
when charindex('live score',o.websiteKeywords)>0 then 'Yes'
when charindex('booking flights',o.websiteKeywords)>0 then 'Yes'
when charindex('book taxi',o.websiteKeywords)>0 then 'Yes'
when charindex('instant money transfer',o.websiteKeywords)>0 then 'Yes'
when charindex(' App ',o.websiteKeywords)>0 then 'Yes'
when charindex('Shopping',o.websiteKeywords)>0 then 'Yes'
when charindex('Online',o.websiteKeywords)>0 then 'Yes'
when charindex('Retail',o.websiteKeywords)>0 then 'Yes'
when charindex('Mobile',o.websiteKeywords)>0 then 'Yes'
when charindex('Songs Download',o.websiteKeywords)>0 then 'Yes'
when charindex('Platform',o.websiteKeywords)>0 then 'Yes'
when charindex('Shopping Cart',o.websiteKeywords)>0 then 'Yes'
when charindex('omni-channel',o.websiteKeywords)>0 then 'Yes'
when charindex('e-commerce',o.websiteKeywords)>0 then 'Yes'
when charindex('telecom',o.websiteKeywords)>0 then 'Yes'
when charindex('travel',o.websiteKeywords)>0 then 'Yes'
when charindex('tourism',o.websiteKeywords)>0 then 'Yes'
when charindex('BFSI',o.websiteKeywords)>0 then 'Yes'
when charindex('songs online',o.websiteKeywords)>0 then 'Yes'
when charindex('rummy online',o.websiteKeywords)>0 then 'Yes'
when charindex('Online banking',o.websiteKeywords)>0 then 'Yes'
when charindex('telecom services provider',o.websiteKeywords)>0 then 'Yes'
when charindex('no credit card needed',o.websiteKeywords)>0 then 'Yes'
when charindex('buy online',o.websiteKeywords)>0 then 'Yes'
when charindex('fast credit',o.GlassDoorDescription)>0 then 'Yes'
when charindex('fast loan',o.GlassDoorDescription)>0 then 'Yes'
when charindex('Spa Deals',o.GlassDoorDescription)>0 then 'Yes'
when charindex('fitness deals',o.GlassDoorDescription)>0 then 'Yes'
when charindex('one stop fashion',o.GlassDoorDescription)>0 then 'Yes'
when charindex('watch latest',o.GlassDoorDescription)>0 then 'Yes'
when charindex('food deals',o.GlassDoorDescription)>0 then 'Yes'
when charindex('online grocery',o.GlassDoorDescription)>0 then 'Yes'
when charindex('popular fashion',o.GlassDoorDescription)>0 then 'Yes'
when charindex('shopper',o.GlassDoorDescription)>0 then 'Yes'
when charindex('food delivery',o.GlassDoorDescription)>0 then 'Yes'
when charindex('live score',o.GlassDoorDescription)>0 then 'Yes'
when charindex('booking flights',o.GlassDoorDescription)>0 then 'Yes'
when charindex('book taxi',o.GlassDoorDescription)>0 then 'Yes'
when charindex('instant money transfer',o.GlassDoorDescription)>0 then 'Yes'
when charindex('App',o.GlassDoorDescription)>0 then 'Yes'
when charindex('Shopping',o.GlassDoorDescription)>0 then 'Yes'
when charindex('Online',o.GlassDoorDescription)>0 then 'Yes'
when charindex('Retail',o.GlassDoorDescription)>0 then 'Yes'
when charindex('Mobile',o.GlassDoorDescription)>0 then 'Yes'
when charindex('Songs Download',o.GlassDoorDescription)>0 then 'Yes'
when charindex('Platform',o.GlassDoorDescription)>0 then 'Yes'
when charindex('Shopping Cart',o.GlassDoorDescription)>0 then 'Yes'
when charindex('omni-channel',o.GlassDoorDescription)>0 then 'Yes'
when charindex('e-commerce',o.GlassDoorDescription)>0 then 'Yes'
when charindex('telecom',o.GlassDoorDescription)>0 then 'Yes'
when charindex('travel',o.GlassDoorDescription)>0 then 'Yes'
when charindex('tourism',o.GlassDoorDescription)>0 then 'Yes'
when charindex('BFSI',o.GlassDoorDescription)>0 then 'Yes'
when charindex('songs online',o.GlassDoorDescription)>0 then 'Yes'
when charindex('rummy online',o.GlassDoorDescription)>0 then 'Yes'
when charindex('Online banking',o.GlassDoorDescription)>0 then 'Yes'
when charindex('telecom services provider',o.GlassDoorDescription)>0 then 'Yes'
when charindex('no credit card needed',o.GlassDoorDescription)>0 then 'Yes'
when charindex('buy online',o.GlassDoorDescription)>0 then 'Yes'
when charindex('music for everyone',o.GlassDoorDescription)>0 then 'Yes'
when charindex('fast credit',o.websitetitle)>0 then 'Yes'
when charindex('fast loan',o.websitetitle)>0 then 'Yes'
when charindex('Spa Deals',o.websitetitle)>0 then 'Yes'
when charindex('fitness deals',o.websitetitle)>0 then 'Yes'
when charindex('one stop fashion',o.websitetitle)>0 then 'Yes'
when charindex('watch latest',o.websitetitle)>0 then 'Yes'
when charindex('food deals',o.websitetitle)>0 then 'Yes'
when charindex('online grocery',o.websitetitle)>0 then 'Yes'
when charindex('popular fashion',o.websitetitle)>0 then 'Yes'
when charindex('shopper',o.websitetitle)>0 then 'Yes'
when charindex('food delivery',o.websitetitle)>0 then 'Yes'
when charindex('live score',o.websitetitle)>0 then 'Yes'
when charindex('booking flights',o.websitetitle)>0 then 'Yes'
when charindex('book taxi',o.websitetitle)>0 then 'Yes'
when charindex('instant money transfer',o.websitetitle)>0 then 'Yes'
when charindex('App',o.websitetitle)>0 then 'Yes'
when charindex('Shopping',o.websitetitle)>0 then 'Yes'
when charindex('Online',o.websitetitle)>0 then 'Yes'
when charindex('Retail',o.websitetitle)>0 then 'Yes'
when charindex('Mobile',o.websitetitle)>0 then 'Yes'
when charindex('Songs Download',o.websitetitle)>0 then 'Yes'
when charindex('Platform',o.websitetitle)>0 then 'Yes'
when charindex('Shopping Cart',o.websitetitle)>0 then 'Yes'
when charindex('omni-channel',o.websitetitle)>0 then 'Yes'
when charindex('e-commerce',o.websitetitle)>0 then 'Yes'
when charindex('telecom',o.websitetitle)>0 then 'Yes'
when charindex('travel',o.websitetitle)>0 then 'Yes'
when charindex('tourism',o.websitetitle)>0 then 'Yes'
when charindex('BFSI',o.websitetitle)>0 then 'Yes'
when charindex('songs online',o.websitetitle)>0 then 'Yes'
when charindex('rummy online',o.websitetitle)>0 then 'Yes'
when charindex('Online banking',o.websitetitle)>0 then 'Yes'
when charindex('telecom services provider',o.websitetitle)>0 then 'Yes'
when charindex('no credit card needed',o.websitetitle)>0 then 'Yes'
when charindex('buy online',o.websitetitle)>0 then 'Yes'
when charindex('music for everyone',o.websitetitle)>0 then 'Yes'
when charindex('fast credit',o.description)>0 then 'Yes'
when charindex('fast loan',o.description)>0 then 'Yes'
when charindex('Spa Deals',o.description)>0 then 'Yes'
when charindex('fitness deals',o.description)>0 then 'Yes'
when charindex('one stop fashion',o.description)>0 then 'Yes'
when charindex('watch latest',o.description)>0 then 'Yes'
when charindex('food deals',o.description)>0 then 'Yes'
when charindex('online grocery',o.description)>0 then 'Yes'
when charindex('popular fashion',o.description)>0 then 'Yes'
when charindex('shopper',o.description)>0 then 'Yes'
when charindex('food delivery',o.description)>0 then 'Yes'
when charindex('live score',o.description)>0 then 'Yes'
when charindex('booking flights',o.description)>0 then 'Yes'
when charindex('book taxi',o.description)>0 then 'Yes'
when charindex('instant money transfer',o.description)>0 then 'Yes'
when charindex('App',o.description)>0 then 'Yes'
when charindex('Shopping',o.description)>0 then 'Yes'
when charindex('Online',o.description)>0 then 'Yes'
when charindex('Retail',o.description)>0 then 'Yes'
when charindex('Mobile',o.description)>0 then 'Yes'
when charindex('Songs Download',o.description)>0 then 'Yes'
when charindex('Platform',o.description)>0 then 'Yes'
when charindex('Shopping Cart',o.description)>0 then 'Yes'
when charindex('omni-channel',o.description)>0 then 'Yes'
when charindex('e-commerce',o.description)>0 then 'Yes'
when charindex('telecom',o.description)>0 then 'Yes'
when charindex('travel',o.description)>0 then 'Yes'
when charindex('tourism',o.description)>0 then 'Yes'
when charindex('BFSI',o.description)>0 then 'Yes'
when charindex('songs online',o.description)>0 then 'Yes'
when charindex('rummy online',o.description)>0 then 'Yes'
when charindex('Online banking',o.description)>0 then 'Yes'
when charindex('telecom services provider',o.description)>0 then 'Yes'
when charindex('no credit card needed',o.description)>0 then 'Yes'
when charindex('buy online',o.description)>0 then 'Yes'
else
'No' 
end as Good_For_MoEngage
FROM            ofrogs.InboundCRM.InboundInput II JOIN
                         ofrogs.InboundCRM.EnrichedProfile IE ON II.id = IE.InboundInputId LEFT OUTER JOIN
                         Organization O ON IE.EmployerName COLLATE Latin1_General_CI_AI = o.Name LEFT OUTER JOIN
                         Industry I ON O.IndustryId = I.id
